### ISSUE TITLE
Counter Strike 1.6    Extra props: Zombie Antidote Gun  Gauss Mod

### ISSUE THREAD

**Issue by SnowbirdCalling** [PerfectScrash/ZP-Special-Mods#1]
How to make an Antidote gun. In the zombie mode, you can target the zombie and turn the zombie into a human. This is just a function of the Gauss gun. Use the left mouse button to shoot the zombie and turn it into a human, but the right mouse button can make the zombie lose its gravity like being The wind blows away the zombies. I don't know how to use Gauss guns to achieve such functions and methods. I saw that some people did this on some servers, but the Maxx files of many detox guns were invalid. . . // At the same time, it is an extra item: Gauss Gun Mod. Its binding key is "3". After purchasing it, use the "3" key of (Switching Knife) to get and use it (Antidote Gun) (Gauss Mod). _ I have found a lot of mods and plug-ins and have not got the desired effect. At the same time, I don't know how to write code... It's a headache..    <zp_extra_adv_antidotegun>..

**Comment by PerfectScrash** [comment]
Please, use this section for report bugs or problems. For requests/suggestions contact me in PM.
